version: "3"
services:
    app:
        container_name: mcstatus-prod
        command: npm start
        restart: always
        environment: 
            - NODE_ENV=production
        ports:
            - '3030:3000'