version: "3"
services:
    app:
        container_name: mcstatus-dev
        command: npm start
        volumes:
            - .:/usr/src/mcstatus
        environment: 
            - NODE_ENV=development
        ports:
            - '3000:3000'