name: Build and test docker image
on:
  release:
    types: [published]
jobs : 
  build-and-push-image:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: https://docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build container image
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: docker.pkg.github.com/selida95/mcstatus/mcstatus_docker:latest
