name: Build and test docker image
on: [push]
jobs : 
  build-and-push-image:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v1
      with: 
        username: ${{ github.actor }}
        password: ${{ secrets.MCSTATUS_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/mcstatus
        tag_with_sha: true
        tag_with_ref: true 